<a href="https://colab.research.google.com/github/JuniorHZ19/ML/blob/main/perceptronsimplepytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch torchvision torchaudio

In [ ]:
import torch
import numpy as np


arraglo_numpy_float64=np.array([[1,2,3,4],
                                [5,3,8,7],
                                [7,2,3,4]],dtype=np.float64)


tensor_trasnformado=torch.from_numpy(arraglo_numpy_float64)

tensor_trasnformado

tensor([[1., 2., 3., 4.],
        [5., 3., 8., 7.],
        [7., 2., 3., 4.]], dtype=torch.float64)

In [67]:
import torch
from torch.utils.data import Dataset
import pandas as pd
import sklearn
from sklearn.preprocessing import StandardScaler


class MiDataSet(Dataset):

  def __init__(self,csv_file):

     data=pd.read_csv(csv_file)

     self.x,self.y = self.limpiezaDatos(data)

     self.samples=self.y.shape[0]


  def __getitem__(self,id):

   return self.x[id],self.y[id]


  def __len__(self):
   return self.samples


  def limpiezaDatos(self,data):

    data=data.dropna(how="all")

    data=data.drop_duplicates()

    data=data.drop(columns=["name","ticket","cabin","boat","body","home.dest"])

    data[["age","fare"]]=data[["age","fare"]].fillna(data[["age","fare"]].mean())

    data["embarked"]=data["embarked"].fillna("S")

    data["age"]=data["age"].astype(int)

    data=pd.get_dummies (data,columns=["sex","embarked"],prefix=["sex","embarked"])

    variables_x=data.drop(columns=["survived"])

    print(variables_x.head())

    print(data["survived"].head())
    self.scaler=StandardScaler()

    variables_x_esclados=self.scaler.fit_transform(variables_x)

    variable_y=data["survived"].values

    datos_x=torch.from_numpy(variables_x_esclados).float()
    datos_y=torch.from_numpy(variable_y).float()

    return datos_x,datos_y







In [79]:
mis_datos=MiDataSet("/content/titanic.csv")

mis_datos.__getitem__(2)


   pclass  age  sibsp  parch      fare  sex_female  sex_male  embarked_C  \
0       1   29      0      0  211.3375           1         0           0   
1       1    0      1      2  151.5500           0         1           0   
2       1    2      1      2  151.5500           1         0           0   
3       1   30      1      2  151.5500           0         1           0   
4       1   25      1      2  151.5500           1         0           0   

   embarked_Q  embarked_S  
0           0           1  
1           0           1  
2           0           1  
3           0           1  
4           0           1  
0    1
1    1
2    0
3    0
4    0
Name: survived, dtype: int64


(tensor([-1.5461, -2.1470,  0.4813,  1.8665,  2.2865,  1.3450, -1.3450, -0.5098,
         -0.3220,  0.6550]),
 tensor(0.))

In [74]:
from torch.utils.data import DataLoader


data_por_lote=DataLoader(mis_datos,batch_size=mis_datos.__len__(),shuffle=True)

datos_features,datos_label=next(iter(data_por_lote))


print(datos_features.shape)

print(datos_label)


torch.Size([1309, 10])
tensor([0., 0., 0.,  ..., 1., 1., 1.])


In [75]:
import torch.nn as nn

class Perceptron(nn.Module):

 def __init__(self,input_size):
  super(Perceptron,self).__init__()

  self.capalineal=nn.Linear(input_size,1)

 def forward(self,x):
    salidaNeurona=torch.sigmoid(self.capalineal(x))
    return salidaNeurona

In [78]:
import torch.optim as optim


input_size=datos_features.shape[1]

PerceptronSimple=Perceptron(input_size)

criterio=nn.BCELoss()

optimizer=optim.SGD(PerceptronSimple.parameters(),lr=0.001)

epochs=9000

for epoch in range(epochs):

  y_predict=PerceptronSimple(datos_features)

  loss=criterio(y_predict,datos_label.view(-1,1))

  loss.backward()

  optimizer.step()


  optimizer.zero_grad()


  print(f'Epoca[{epoch+1}],Perdida: {loss.item():.4f}')


def escalarNuevaData(data):

    scaler=StandardScaler()

    datos_escalados=scaler.fit_transform(data)

    datos_x_tensor=torch.from_numpy(datos_escalados).float()

    return datos_x_tensor

nuevo_x=escalarNuevaData([[1,29,0,0,211,1,0,0,0,1]])

y_predict=PerceptronSimple(nuevo_x)

print(y_predict)

Se truncaron las últimas líneas 5000 del resultado de transmisión.
Epoca[4002],Perdida: 0.4886
Epoca[4003],Perdida: 0.4886
Epoca[4004],Perdida: 0.4886
Epoca[4005],Perdida: 0.4886
Epoca[4006],Perdida: 0.4886
Epoca[4007],Perdida: 0.4886
Epoca[4008],Perdida: 0.4886
Epoca[4009],Perdida: 0.4885
Epoca[4010],Perdida: 0.4885
Epoca[4011],Perdida: 0.4885
Epoca[4012],Perdida: 0.4885
Epoca[4013],Perdida: 0.4885
Epoca[4014],Perdida: 0.4885
Epoca[4015],Perdida: 0.4885
Epoca[4016],Perdida: 0.4885
Epoca[4017],Perdida: 0.4885
Epoca[4018],Perdida: 0.4884
Epoca[4019],Perdida: 0.4884
Epoca[4020],Perdida: 0.4884
Epoca[4021],Perdida: 0.4884
Epoca[4022],Perdida: 0.4884
Epoca[4023],Perdida: 0.4884
Epoca[4024],Perdida: 0.4884
Epoca[4025],Perdida: 0.4884
Epoca[4026],Perdida: 0.4884
Epoca[4027],Perdida: 0.4883
Epoca[4028],Perdida: 0.4883
Epoca[4029],Perdida: 0.4883
Epoca[4030],Perdida: 0.4883
Epoca[4031],Perdida: 0.4883
Epoca[4032],Perdida: 0.4883
Epoca[4033],Perdida: 0.4883
Epoca[4034],Perdida: 0.4883
Epoca[403