<a href="https://colab.research.google.com/github/JuniorHZ19/ML/blob/main/perceptronmulticapa5.0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch torchvision

In [2]:
import torch
from torch.utils.data import Dataset
import pandas as pd
import sklearn
from sklearn.preprocessing import StandardScaler



class MiDataSet(Dataset):

  def __init__(self,csv_file):

     data=pd.read_csv(csv_file)

     self.x,self.y= self.limpiezaDatos(data)

     self.samples=self.y.shape[0]


  def __getitem__(self,id):

   return self.x[id],self.y[id]


  def __len__(self):
   return self.samples


  def limpiezaDatos(self,data):

    data=data.dropna(how="all")

    data=data.drop_duplicates()

    data=data.drop(columns=["name","ticket","cabin","boat","body","home.dest"])

    data[["age","fare"]]=data[["age","fare"]].fillna(data[["age","fare"]].mean())

    data["embarked"]=data["embarked"].fillna("S")

    data["age"]=data["age"].astype(int)

    data=pd.get_dummies (data,columns=["sex","embarked"],prefix=["sex","embarked"])

    variables_x=data.drop(columns=["survived"])

    print(variables_x.head())

    print(data["survived"].head())
    self.scaler=StandardScaler()

    variables_x_esclados=self.scaler.fit_transform(variables_x)

    variable_y=data["survived"].values


    datos_x=torch.from_numpy(variables_x_esclados).float()

    datos_y=torch.from_numpy(variable_y).float()



    return datos_x,  datos_y







In [3]:
import sklearn

from sklearn.model_selection import train_test_split

mis_datos=MiDataSet("/content/titanic.csv")



X_entrenamiento, X_prueba, y_entrenamiento, y_prueba = train_test_split(mis_datos.x, mis_datos.y, test_size=0.3, random_state=0,stratify=mis_datos.y)

print(X_entrenamiento.shape)

print(X_prueba)

print(y_entrenamiento.shape)

print(y_prueba)




   pclass  age  sibsp  parch      fare  sex_female  sex_male  embarked_C  \
0       1   29      0      0  211.3375           1         0           0   
1       1    0      1      2  151.5500           0         1           0   
2       1    2      1      2  151.5500           1         0           0   
3       1   30      1      2  151.5500           0         1           0   
4       1   25      1      2  151.5500           1         0           0   

   embarked_Q  embarked_S  
0           0           1  
1           0           1  
2           0           1  
3           0           1  
4           0           1  
0    1
1    1
2    0
3    0
4    0
Name: survived, dtype: int64
torch.Size([916, 10])
tensor([[ 0.8419, -0.5960, -0.4791,  ..., -0.5098, -0.3220,  0.6550],
        [-1.5461,  1.3428, -0.4791,  ..., -0.5098, -0.3220,  0.6550],
        [ 0.8419, -1.8368,  2.4020,  ..., -0.5098, -0.3220,  0.6550],
        ...,
        [-0.3521,  3.1264, -0.4791,  ..., -0.5098, -0.3220,  0.655

In [9]:
y_entrenamiento

tensor([0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
        1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0.,
        1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1.,
        0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0.,
        1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
        0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0.,
        1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0.,
        0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0.,
        0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
        0., 0., 0., 0., 1., 1., 0., 1., 

In [10]:



from torch.utils.data import DataLoader, TensorDataset



conjunto_entrenamiento = TensorDataset(X_entrenamiento, y_entrenamiento)

conjunto_prueba = TensorDataset(X_prueba, y_prueba)

data_por_lote_entrenamiento=DataLoader(conjunto_entrenamiento,batch_size=10,shuffle=True)

data_por_por_lote_test=DataLoader(conjunto_prueba,batch_size=10,shuffle=True)



#datos_features_train,datos_label_train=next(iter(data_por_lote_entrenamiento))

#datos_features_test,datos_label_test=next(iter(data_por_por_lote_test))


print(data_por_lote_entrenamiento.batch_size)




10


In [ ]:
import torch.nn as nn
import torch.nn.functional as F

modelo=torch.Sequential(

                        torch.nn.Linear(input_size,3),
                        torch.nn.ReLU(),

                        torch.nn.Linear(3,4),
                        torch.nn.ReLU(),

                        torch.nn.Linear(4,1),
                        torch.nn.Sigmoid()
)

AttributeError: ignored

In [72]:
import torch.nn as nn
import torch.nn.functional as F



class PerceptronMulticapa(nn.Module):

   def __init__(self,input_size):
    super(PerceptronMulticapa,self).__init__()

    self.capa_oculta1=nn.Linear(input_size,5)

    self.dropout=nn.Dropout(0.5)
    self.capa_salida =nn.Linear(1,1)

   def forward(self,x):

     x=self.capa_oculta1(x)
     x=F.relu(x)

     x=self.dropout(x)
     output=self.capa_salida(x)



     return output


In [73]:

if torch.cuda.is_available():
    print("CUDA está disponible.")
    device = torch.device("cuda")
else:
    print("CUDA no está disponible. Se utilizará la CPU.")
    device = torch.device("cpu")

CUDA no está disponible. Se utilizará la CPU.


In [93]:
import numpy as np


#funcion clasificador:
def clasificador(y_pred_test):

  umbral = 0.6
  y_pred_test_binario = (y_pred_test >= umbral).to(torch.float32)
  return y_pred_test_binario

#funcion acutity:

def accuracy(y_test, y_real):
    correctos = torch.sum(y_test == y_real).item()
    return correctos / len(y_test)


import torch.optim as optim



def TrainMLP(modelo,epochs,optimisador,criterio,input_size,data_Loader_entrenamiento,data_Loader_test):

 for epoch in range(epochs):

  total_train_loss = 0.0
  num_train_batches = len(data_Loader_entrenamiento)
  modelo.train()

  for x_entrenamiento,y_entrenamiento in (data_Loader_entrenamiento):
   x_entrenamiento,y_entrenamiento=x_entrenamiento.to(device),y_entrenamiento.to(device)

   y_predict=modelo(x_entrenamiento)
   loss=criterio(y_predict,y_entrenamiento.view(-1,1))

   loss.backward()
   optimisador.step()
   optimisador.zero_grad()
   total_train_loss+=loss.item()

  modelo.eval()
  with torch.no_grad():
    total_test_accuracy = 0.0
    num_test_batches = len(data_Loader_test)

    for X_prueba,y_prueba in (data_Loader_test):

     X_prueba,y_prueba=X_prueba.to(device),y_prueba.to(device)
     y_predict_test=modelo(X_prueba)
     y_predict_test_sig=torch.sigmoid(y_predict_test)
     y_predic_test_clasificado=clasificador(y_predict_test_sig)
     Precision=accuracy(y_predic_test_clasificado,y_prueba.view(-1,1))
     total_test_accuracy += Precision

  avg_test_accuracy = (total_test_accuracy / num_test_batches)
  avg_train_loss=(total_train_loss/num_train_batches)
  print(f'Epoca[{epoch+1}], Perdida: {avg_train_loss:.4f},Accuryty:{avg_test_accuracy:.4f}')





#-----------------------------------------------------------------------------------------------

input_sizes=10

PerceptronMulti=PerceptronMulticapa(input_sizes)

criterios=nn.BCEWithLogitsLoss() # automaticamente aplica el sigmoide a la capa de salida y clasfica 0 -1 para el loss

optimizer=optim.Adam(PerceptronMulti.parameters(),lr=0.00001)

epocas=8500

PerceptronMulti=PerceptronMulti.to(device)

TrainMLP(PerceptronMulti,epocas,optimizer,criterios,input_sizes,data_por_lote_entrenamiento,data_por_por_lote_test)



#nuevo datos:

def escalarNuevaData(data):

    scaler=StandardScaler()

    datos_escalados=scaler.fit_transform(data)

    datos_x_tensor=torch.from_numpy(datos_escalados).float()

    return datos_x_tensor

nuevo_x=escalarNuevaData([[1,29,0,0,211,1,0,0,0,1]])

y_predict=PerceptronMulti(nuevo_x)

print(clasificador(y_predict))



Se truncaron las últimas líneas 5000 del resultado de transmisión.
Epoca[3502], Perdida: 0.5730,Accuryty:0.6800
Epoca[3503], Perdida: 0.5732,Accuryty:0.6742
Epoca[3504], Perdida: 0.5741,Accuryty:0.6683
Epoca[3505], Perdida: 0.5734,Accuryty:0.6742
Epoca[3506], Perdida: 0.5730,Accuryty:0.6683
Epoca[3507], Perdida: 0.5729,Accuryty:0.6742
Epoca[3508], Perdida: 0.5733,Accuryty:0.6742
Epoca[3509], Perdida: 0.5736,Accuryty:0.6742
Epoca[3510], Perdida: 0.5730,Accuryty:0.6683
Epoca[3511], Perdida: 0.5735,Accuryty:0.6683
Epoca[3512], Perdida: 0.5732,Accuryty:0.6742
Epoca[3513], Perdida: 0.5733,Accuryty:0.6742
Epoca[3514], Perdida: 0.5728,Accuryty:0.6742
Epoca[3515], Perdida: 0.5728,Accuryty:0.6742
Epoca[3516], Perdida: 0.5728,Accuryty:0.6767
Epoca[3517], Perdida: 0.5730,Accuryty:0.6767
Epoca[3518], Perdida: 0.5725,Accuryty:0.6767
Epoca[3519], Perdida: 0.5733,Accuryty:0.6708
Epoca[3520], Perdida: 0.5723,Accuryty:0.6767
Epoca[3521], Perdida: 0.5724,Accuryty:0.6767
Epoca[3522], Perdida: 0.5730,Accu

In [ ]:


y_pred_multiclases = torch.tensor([[0.1, 1.8, 0.8, 0.4, 2],
                                   [0.5, 2, 3.5, 5, 2.1]])

def clasificador(y_pred_test):

   max_values_tensor = torch.empty((0,), dtype=torch.float32)

   for tensor in y_pred_test:

     max_values, max_indices  = torch.max(tensor, dim=0)

     max_values_tensor = torch.cat((max_values_tensor, max_indices.unsqueeze(0)))

   return max_values_tensor

print(clasificador(y_pred_multiclases))


tensor([4., 3.])
